apiVersion: v1
kind: Service
metadata:
  name:  client-service

spec:
  type: LoadBalancer
  ports: 
    - protocol: TCP
      port: 80
      targetPort: 3000
      
  
  selector:
    component: web

